# Coturn TURN SERVER configuration file

listening-port=3478
tls-listening-port=5349

external-ip=52.202.87.135

user=webchat:qwerty42


cert=/usr/local/etc/webchatturn.crt
pkey=/usr/local/etc/webchatturn.key

log-file=/var/log/coturn.log